"use client";

import { Box, SimpleGrid, Heading, Text, Flex, Icon, HStack } from "@chakra-ui/react";
import { LuCpu, LuShieldCheck, LuZap, LuLock } from "react-icons/lu";

const techPillars = [
  {
    title: "ERC-8183 Agentic Escrow",
    description: "Programmable escrow protocol standard designed specifically for autonomous AI agent commercial transactions.",
    tag: "SMART CONTRACT",
    icon: LuLock,
  },
  {
    title: "Arc Native USDC Gas",
    description: "Built on Arc blockchain rails providing sub-second settlement finality with zero gas volatility for micro-payouts.",
    tag: "BLOCKCHAIN RAILS",
    icon: LuZap,
  },
  {
    title: "Device Hardware Registry",
    description: "On-chain registry validating cryptographic EIP-712 signatures generated by contributor device Secure Enclaves.",
    tag: "PROVENANCE ENGINE",
    icon: LuShieldCheck,
  },
  {
    title: "Autonomous Evaluator Agents",
    description: "Decentralized verifier agents scoring multi-modal dataset submissions before triggering fund disbursal.",
    tag: "AI VERIFICATION",
    icon: LuCpu,
  },
];

export function TechStackSection() {
  return (
    <Box py={{ base: 16, md: 24 }} bg="bg" borderBottomWidth="1px" borderColor="border.DEFAULT">
      <Flex direction="column" mb={12}>
        <HStack gap={2} mb={2}>
          <Text textStyle="label-mono" color="secondary" fontWeight="700">
            // PROTOCOL ARCHITECTURE
          </Text>
        </HStack>
        <Heading as="h2" textStyle="headline-lg" color="primary" fontSize={{ base: "28px", md: "36px" }}>
          Engineered for Trustless Data Commerce
        </Heading>
      </Flex>

      <SimpleGrid columns={{ base: 1, md: 2, lg: 4 }} gap={6}>
        {techPillars.map((pillar) => (
          <Box
            key={pillar.title}
            p={7}
            bg="surfaceNeutral"
            border="1px solid"
            borderColor="primary"
            transition="all 0.25s cubic-bezier(0.4, 0, 0.2, 1)"
            _hover={{
              bg: "bg.panel",
              transform: "translate(-4px, -4px)",
              borderColor: "primary",
              boxShadow: "6px 6px 0px 0px #000000",
            }}
          >
            <Flex justify="space-between" align="center" mb={6}>
              <Box p={3} bg="primary" color="onPrimary">
                <Icon as={pillar.icon} boxSize={5} />
              </Box>
              <Text textStyle="label-mono" color="fg.subtle" fontSize="10px">
                {pillar.tag}
              </Text>
            </Flex>

            <Heading as="h3" textStyle="body-lg" fontWeight="700" color="primary" mb={3} fontSize="17px">
              {pillar.title}
            </Heading>

            <Text textStyle="body-md" color="fg.muted" fontSize="14px" lineHeight="1.5">
              {pillar.description}
            </Text>
          </Box>
        ))}
      </SimpleGrid>
    </Box>
  );
}
